#!/usr/bin/env python3
"""
TradeMaster v2 - Comprehensive Backtest
15 stocks × Top 10 strategies
"""

import pandas as pd
import numpy as np
from datetime import datetime
from backtest import BacktestEngine
from core import PluginRegistry
import warnings
import sys
import os
warnings.filterwarnings('ignore')

# 15 支股票
STOCKS = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'NVDA', 'META', 'TSLA', 'NFLX', 'AMD', 'INTC', 'CRM', 'ORCL', 'ADBE', 'PYPL', 'SHOP']

# Top 10 策略
TOP_STRATEGIES = [
    'RSI_Mean_Reversion',
    'MACD_Trend', 
    'ADX_Trend',
    'Bollinger_Bounce',
    'Stochastic_Oversold',
    'Three_MA_Crossover',
    'Dual_MA_Crossover',
    'RSI_Divergence',
    'CCI_MeanRev',
    'Williams_Range'
]

def load_data(symbol):
    """從 stooq 載入數據"""
    filepath = f"data/historical/{symbol}.csv"
    if os.path.exists(filepath):
        df = pd.read_csv(filepath, index_col=0, parse_dates=True)
        return df
    return None

def run_comprehensive_backtest():
    """執行完整回測"""
    
    engine = BacktestEngine(initial_capital=100000)
    registry = PluginRegistry()
    registry.discover_plugins('strategies/')
    
    results = []
    total_tests = len(STOCKS) * len(TOP_STRATEGIES)
    current = 0
    
    print(f"\n{'='*60}")
    print(f"TradeMaster v2 - 完整回測")
    print(f"時間: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print(f"股票: {len(STOCKS)} 支")
    print(f"策略: {len(TOP_STRATEGIES)} 個")
    print(f"總測試數: {total_tests}")
    print(f"{'='*60}\n")
    
    for symbol in STOCKS:
        print(f"\n📊 {symbol}")
        print(f"{'-'*40}")
        
        # 載入數據
        data = load_data(symbol)
        if data is None:
            print(f"   ⚠️  數據不存在，嘗試下載...")
            os.system(f"python3 download_data.py --symbol {symbol}")
            data = load_data(symbol)
        
        if data is None:
            print(f"   ❌ 數據載入失敗")
            continue
        
        print(f"   ✅ 數據已載入: {len(data)} 天")
        
        for strat_name in TOP_STRATEGIES:
            current += 1
            status = f"[{current}/{total_tests}]"
            
            if strat_name not in [s[0] for s in registry.list_strategies()]:
                print(f"   {status} {strat_name}: ❌ 策略不存在")
                continue
            
            try:
                strat_cls = registry.get_strategy(strat_name)
                strat = strat_cls()
                result = engine.run(symbol, strat, data, strat_name)
                
                sharpe = result.annualized_return / result.volatility if result.volatility > 0 else 0
                max_dd = abs(result.max_drawdown) if result.max_drawdown else 0
                
                results.append({
                    'stock': symbol,
                    'strategy': strat_name,
                    'return': result.total_return * 100,
                    'sharpe': sharpe,
                    'max_dd': max_dd,
                    'trades': result.total_trades,
                    'win_rate': result.win_rate if hasattr(result, 'win_rate') else 0
                })
                
                emoji = "📈" if result.total_return > 0 else "📉"
                print(f"   {status} {strat_name}: {emoji} {result.total_return*100:.1f}% | 夏普 {sharpe:.2f} | DD {max_dd:.1f}%")
                
            except Exception as e:
                print(f"   {status} {strat_name}: ❌ {str(e)[:50]}")
    
    # 結果摘要
    print(f"\n{'='*60}")
    print("📊 結果摘要")
    print(f"{'='*60}")
    
    df = pd.DataFrame(results)
    
    if len(df) > 0:
        df_sorted = df.sort_values('sharpe', ascending=False)
        top10 = df_sorted.head(10)
        
        print(f"\n🏆 Top 10 策略:")
        for i, (_, row) in enumerate(top10.iterrows(), 1):
            print(f"   {i}. {row['stock']} - {row['strategy']}")
            print(f"      📈 {row['return']:.1f}% | 夏普 {row['sharpe']:.2f} | DD {row['max_dd']:.1f}%")
        
        # 保存
        timestamp = datetime.now().strftime('%Y%m%d_%H%M')
        report_file = f"docs/comprehensive_backtest_{timestamp}.md"
        csv_file = f"docs/comprehensive_backtest_{timestamp}.csv"
        df.to_csv(csv_file, index=False)
        
        with open(report_file, 'w') as f:
            f.write(f"# TradeMaster v2 - 完整回測報告\n\n")
            f.write(f"**時間**: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n")
            f.write(f"## 🏆 Top 10 策略\n\n")
            for i, (_, row) in enumerate(top10.iterrows(), 1):
                f.write(f"### {i}. {row['stock']} - {row['strategy']}\n")
                f.write(f"- 報酬率: {row['return']:.2f}%\n")
                f.write(f"- 夏普比率: {row['sharpe']:.2f}\n")
                f.write(f"- 最大回撤: {row['max_dd']:.2f}%\n\n")
            f.write(f"\n---\n*Generated by TradeMaster v2*\n")
        
        print(f"\n✅ 報告已保存:")
        print(f"   📄 {report_file}")
        print(f"   📊 {csv_file}")
    
    print(f"\n{'='*60}")
    print("✅ 完整回測完成!")
    print(f"{'='*60}\n")

if __name__ == "__main__":
    run_comprehensive_backtest()
