#!/usr/bin/env python3
"""
Top 10 策略回測腳本
找出最佳的 10 個策略參數，並應用到所有配置的股票上
"""

import pandas as pd
import json
from datetime import datetime

# 配置的股票清單 - 正式回測
SYMBOLS = [
    'TSLA',  # Tesla
    'AAPL',  # Apple
    'AMZN',  # Amazon
    'NVDA',  # NVIDIA
    'META',  # Meta
    'MSFT',  # Microsoft
    'UBER',  # Uber
    'INTC',  # Intel
    'AMD',   # AMD
    'RKLB',  # Rocket Lab
    'WDC',   # Western Digital
    'MU',    # Micron
    'TSM',   # TSMC
    'ORCL',  # Oracle
    'DELL',  # Dell
]

# 讀取並重命名 return 列避免衝突
df1 = pd.read_csv('data/backtest_results/stooq_v2_results.csv')
df2 = pd.read_csv('data/backtest_results/rsi2_results.csv')
df3 = pd.read_csv('data/backtest_results/trend_filtered_results.csv')

# 重命名 return 列
for df in [df1, df2, df3]:
    if 'return' in df.columns:
        df.rename(columns={'return': 'annual_return'}, inplace=True)

# 合併並清理數據
all_results = pd.concat([df1, df2, df3], ignore_index=True)
all_results = all_results.fillna(0)

# 去重（按 symbol, sharpe, params）
unique_results = all_results.drop_duplicates(subset=['symbol', 'params'])

# 按 Sharpe 排序，取前 10
top10 = unique_results.nlargest(10, 'sharpe')

print("\n🏆 TOP 10 最佳策略參數:")
print("=" * 80)
strategies = []
for i, row in enumerate(top10.itertuples(), 1):
    strat = {
        'rank': i,
        'symbol': row.symbol,
        'sharpe': round(row.sharpe, 4),
        'annual_return_pct': round(row.annual_return * 100, 2),
        'max_dd_pct': round(row.max_dd * 100, 2),
        'params': row.params
    }
    strategies.append(strat)
    print(f"{i}. {row.symbol}: Sharpe={row.sharpe:.2f}, Return={row.annual_return*100:.1f}%, MaxDD={row.max_dd*100:.1f}%")
    print(f"   參數: {row.params}")
    print()

# 應用到所有配置的股票
print("\n🚀 應用 Top 10 策略到所有配置股票...")
print("=" * 80)

applied_results = []

for strat in strategies:
    # 找出這個策略參數在所有股票上的結果
    matching = unique_results[unique_results['params'] == strat['params']]
    
    for _, row in matching.iterrows():
        if row['symbol'] in SYMBOLS:
            applied_results.append({
                'strategy_rank': strat['rank'],
                'base_symbol': strat['symbol'],
                'applied_symbol': row['symbol'],
                'sharpe': round(row['sharpe'], 4),
                'annual_return_pct': round(row['annual_return'] * 100, 2),
                'max_dd_pct': round(row['max_dd'] * 100, 2),
                'total_trades': int(row['total_trades'] or 0),
                'params': strat['params']
            })

applied_df = pd.DataFrame(applied_results)

# 按 Sharpe 排序
applied_df = applied_df.sort_values('sharpe', ascending=False)

print("\n📈 應用結果 (策略 × 股票):")
print("=" * 80)
print(applied_df.to_string(index=False))

# 生成報告
report = f"""# TradeMaster v2 - Top 10 策略回測報告

**生成時間**: {datetime.now().strftime('%Y-%m-%d %H:%M')}

---

## 🏆 Top 10 策略排行榜

| 排名 | 標的 | Sharpe | 報酬率 | 最大回撤 | 策略參數 |
|------|------|--------|--------|----------|----------|
"""

for strat in strategies:
    report += f"| {strat['rank']} | {strat['symbol']} | **{strat['sharpe']:.2f}** | {strat['annual_return_pct']:.1f}% | {strat['max_dd_pct']:.1f}% | `{strat['params']}` |\n"

report += f"""

---

## 📊 策略 × 股票 應用結果

共 {len(applied_df)} 個策略-股票組合

### 按 Sharpe 排序

| 排名 | 策略來源 | 應用標的 | Sharpe | 報酬率 | 最大回撤 | 交易次數 |
|------|----------|----------|--------|--------|----------|----------|
"""

for idx, (i, row) in enumerate(applied_df.head(30).iterrows(), 1):
    report += f"| {idx} | {row['base_symbol']} | {row['applied_symbol']} | **{row['sharpe']:.2f}** | {row['annual_return_pct']:.1f}% | {row['max_dd_pct']:.1f}% | {row['total_trades']} |\n"

# 統計摘要
if len(applied_df) > 0:
    avg_sharpe = applied_df['sharpe'].mean()
    avg_return = applied_df['annual_return_pct'].mean()
    avg_maxdd = applied_df['max_dd_pct'].mean()
    qualified = applied_df[(applied_df['sharpe'] > 1.5) & (applied_df['annual_return_pct'] > 20) & (applied_df['max_dd_pct'] < 30)]

report += f"""

---

## 📈 統計摘要

| 指標 | 數值 |
|------|------|
| 策略-股票組合數 | {len(applied_df)} |
| 平均 Sharpe | {avg_sharpe:.2f} |
| 平均報酬率 | {avg_return:.1f}% |
| 平均最大回撤 | {avg_maxdd:.1f}% |
| 達標組合數 (Sharpe>1.5, Return>20%, MaxDD<30%) | {len(qualified)} |

---

## 💡 關鍵發現

1. **最佳策略**: {applied_df.iloc[0]['base_symbol']} 的策略 Sharpe 達到 {applied_df.iloc[0]['sharpe']:.2f}
2. **最佳應用標的**: {applied_df.iloc[0]['applied_symbol']}
3. **達標率**: {len(qualified)/len(applied_df)*100:.1f}% ({len(qualified)}/{len(applied_df)})

---

## 📁 數據文件

- `data/backtest_results/stooq_v2_results.csv`
- `data/backtest_results/rsi2_results.csv`
- `data/backtest_results/trend_filtered_results.csv`

---

*Generated by TradeMaster v2*
"""

# 保存報告
report_path = 'reports/TOP10_STRATEGY_REPORT.md'
with open(report_path, 'w', encoding='utf-8') as f:
    f.write(report)

print(f"\n✅ 報告已保存: {report_path}")

# 保存 JSON 結果
json_path = 'reports/top10_results.json'
with open(json_path, 'w', encoding='utf-8') as f:
    json.dump({
        'top_strategies': strategies,
        'applied_results': applied_df.to_dict('records'),
        'summary': {
            'total_combinations': len(applied_df),
            'avg_sharpe': round(avg_sharpe, 4),
            'avg_return': round(avg_return, 2),
            'avg_maxdd': round(avg_maxdd, 2),
            'qualified_count': len(qualified)
        }
    }, f, ensure_ascii=False, indent=2)

print(f"✅ JSON 數據已保存: {json_path}")

# 打印摘要
print(f"\n📊 摘要:")
print(f"   - Top 10 策略: {len(strategies)} 個")
print(f"   - 策略×股票組合: {len(applied_df)} 個")
print(f"   - 達標組合 (Sharpe>1.5, Return>20%, MaxDD<30%): {len(qualified)} 個")
print(f"   - 平均 Sharpe: {avg_sharpe:.2f}")
